### ISSUE TITLE
time taken by as.big.matrix

### ISSUE THREAD

**Issue by YuliZheng** [YaohuiZeng/biglasso_reproduce#1]
Hi, I notice that you didn't take the running time of as.big.matrix(x) into account. I don't think it is fair to let glmnet and other packages use barely x and biglasso use x.bm (big.matrix form of x). Acctually, in my experiment, as.big.matrix(x) can take a lot of time. So may by I think you should add this time to make the result more convincable.

**Comment by pbreheny** [comment]
I see your point, but disagree. Setting up the big matrix object is done so that out-of-core computing can be carried out if the data exceeds available RAM.  glmnet doesn't even work in this scenario, so there is no real comparison to be made.  The timings describe how long it takes the algorithm to fit the model. If out-of-core computing were not an issue, no big matrix object would need to be created, and the time would remain the same. It seems unreasonable to penalize biglasso for providing the option to fit data sets larger than RAM.

You do raise a good point, however, that perhaps biglasso should provide the option to work on regular X objects without converting to big matrix, as that would certainly speed up its use on smaller data sets.  Wasn't what biglasso was designed for, but might be nice to have the option.
